# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
Description: Aurora Serverless DB

Parameters:
  DbUserName:
    Type: String
  DbPassword:
    Type: String
    NoEcho: True
  DbName:
    Type: String
  DbMinCapacity:
    Type: Number
  DbMaxCapacity:
    Type: Number
  PrivateSubnets:
    Type: String
  VpcId:
    Type: String
  FargateSecGroupId:
    Type: String

Resources:
  RdsSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: description
      SubnetIds: !Split [',', !Ref PrivateSubnets]
  PostgresRdsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: ECS Security Group
      VpcId: !Ref VpcId
  PostgresRdsSecurityGroupPostgresInboundFargate:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref PostgresRdsSecurityGroup
      IpProtocol: tcp
      FromPort: '5432'
      ToPort: '5432'
      SourceSecurityGroupId: !Ref FargateSecGroupId
  PostgresRdsCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      DBClusterParameterGroupName:
        Ref: PostgresRdsClusterParameterGroup
      DBSubnetGroupName:
        Ref: RdsSubnetGroup
      DatabaseName: !Ref DbName
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: 10.2
      Port: 5432
      StorageEncrypted: true
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: !Ref DbMinCapacity
        MaxCapacity: !Ref DbMaxCapacity
        SecondsUntilAutoPause: 3600
      VpcSecurityGroupIds:
      - !Ref PostgresRdsSecurityGroup
      MasterUserPassword:
        Ref: DbPassword
      MasterUsername:
        Ref: DbUserName
  PostgresRdsClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: "CloudFormation Aurora Cluster Parameter Group"
      Family: aurora-postgresql10
      Parameters:
        timezone: UTC

Outputs:
  DBIdentifier:
    Value: !Ref PostgresRdsCluster
  EndpointUrl:
    Value: !GetAtt PostgresRdsCluster.Endpoint.Address
  EndpointPort:
    Value: !GetAtt PostgresRdsCluster.Endpoint.Port

